### ISSUE TITLE
Eye detection broken in new update

### ISSUE THREAD

**Issue by Michaelwhite34** [YadiraF/DECA#50]
Not sure which update,I haven't updated for a while.
Before :
![1_vis](https://user-images.githubusercontent.com/72028833/131101015-897ef15c-9674-4f09-9412-88aacdb7a16f.jpg)
After : 
![1_vis](https://user-images.githubusercontent.com/72028833/131101208-6128af92-3233-4d40-bb96-8b79697b2053.jpg)

**Comment by YadiraF** [comment]
Hey thanks for the info, this is because I updated the scale_factor when cropping the image:
Here: https://github.com/YadiraF/DECA/blob/1749e870098d7058f544dbefd742010212dba1b8/demos/demo_reconstruct.py#L37
from default (1.25) to scale=1.4
But it should be 1.25 to make the model work better, now it was fixed :)
